// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuHQCVTfwVxpXcgX3r11GFXHKvKFf_Rtw',
    appId: '1:405106089054:web:416d2d331bb7bcf03268cf',
    messagingSenderId: '405106089054',
    projectId: 'review-food-app-c0757',
    authDomain: 'review-food-app-c0757.firebaseapp.com',
    storageBucket: 'review-food-app-c0757.appspot.com',
    measurementId: 'G-X27X90270S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG_RrTte7N1H3er3ul86FvyJEUH8iQ7qc',
    appId: '1:405106089054:android:2415d97192a94a703268cf',
    messagingSenderId: '405106089054',
    projectId: 'review-food-app-c0757',
    storageBucket: 'review-food-app-c0757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFLAu_CUiJMLbBOU6-Z9uzSvktgIWmkI',
    appId: '1:405106089054:ios:1431a748fe37873e3268cf',
    messagingSenderId: '405106089054',
    projectId: 'review-food-app-c0757',
    storageBucket: 'review-food-app-c0757.appspot.com',
    iosBundleId: 'com.awesome.foodReview',
  );
}
